# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'automation-j2objc' do

pod 'j2objc-shared', :path => '../shared/build'
end

target 'automation-j2objcTests' do

end
